Checked the length of key for checker framework
stleary/JSON-java pull request #583
Opened 2021-01-27 06:08 UTC by ek08

Checked the length of key IN JSONObject  for Checker Framework

2021-01-28 02:04 UTC, stleary commented
**What problem does this code solve?**
JavaCheck fails due to not being able to detect that zero-length keys are disallowed. I don't think there is any change to functionality.

**Risks**
Low

**Changes to the API?**
No

**Will this require a new release?**
No

**Should the documentation be updated?**
No

**Does it break the unit tests?**
No

**Was any code refactored in this commit?**
No

**Review status**
**APPROVED**

Starting 3-day comment window.

2021-01-28 02:10 UTC, johnjaylward commented
I don't see what this change is adding to the code. The key can not be 0 length at that spot. Also, I would argue that the logic chosen for the check is wrong.

I'd argue it should look like this if you feel the check needs to be added

```java
if (key.length() == 0 || Character.isLowerCase(key.charAt(0))) {
    return null;
}
```

2021-01-28 02:11 UTC, johnjaylward requested changes
Check is not valid

2021-01-28 10:09 UTC, ek08 commented
> I don't see what this change is adding to the code. The key can not be 0 length at that spot. Also, I would argue that the logic chosen for the check is wrong.
> 
> I'd argue it should look like this if you feel the check needs to be added
> 
> ```java
> if (key.length() == 0 || Character.isLowerCase(key.charAt(0))) {
>     return null;
> }
> ```

Thanks for the correction. I agree with you that the length of key cannot be 0 length at that spot. So the logic of the check should be changed to 
```
if (key.length() == 0 || Character.isLowerCase(key.charAt(0)))

2021-01-30 00:54 UTC, stleary commented
Approval restored.

2021-02-02 01:48 UTC, merged