checking .length() is faster than .equals("")
stleary/JSON-java pull request #665
Opened 2022-02-21 03:13 UTC by unlucku

Very minor change, when checking if a string has no characters or not then string.length() == 0 is always faster than string.equals("")
This only effects the stringToValue method

2022-02-21 07:49 UTC, stleary commented
Have you considered that the existing code provides protection in case the string being compared has somehow been set to null?

2022-02-23 15:50 UTC, unlucku commented
I did actually, I was going to add null checks originally till I remembered that instanceof returns false if the value checked is null. I checked the places stringToValue was called in commit 291e04485ca2ed35462dbf5d5ec70ac3577a8fba: 
For XML.java line 370 has a preceending check that throws an error if the value passed does not pass the instanceof check and in lines 417 and 420 dont need either check as it already has a instanceof and length check in the if blocks, so the value cannot be null when passed to stringToValue.
For JSONObject.java the function is only called by JSONTokener.java on line 473 which also already has a length check right before it (More on this at the end) and is returned from a trim function meaning in this case it cant be null either. We can actually remove the check preceding it if we rearrange the code a bit. I did not do this as I was unsure of the exact use of that exception.

In commit 71488150bafad6ee2b6e1449242e8127ecb0c2f9 I added the instanceof checks along with length != 0 (since .equals calls instanceof anyways), I omitted it in Cookie.java as the name is a result from trim.

Let me know if you have anymore questions!

2022-03-05 05:44 UTC, unlucku commented
Hope that I can get an opinion on this @stleary

2022-03-05 16:44 UTC, stleary commented
The criteria that I try to follow for code reviews is that the change should satisfy one or more of:

- A compelling improvement to the existing code.
- Fixes an egregious bug.
- Does not change existing behavior.

This change does not qualify, so it is a lower priority. Optimizing the code for speed is reasonable, so no problem there. But it seems to me this change makes the code less safe. Protecting code from NullPointerExceptions is a core principle, for me at least. Try finding a safer way to speed up the code.

2022-05-07 13:53 UTC, johnjaylward requested changes

2022-05-07 13:53 UTC, johnjaylward commented on src/main/java/org/json/JSONObject.java
>      public static Object stringToValue(String string) {
As this is a public method, the contract has to remain the same. This means supporting a `null` parameter value.

2022-05-07 13:53 UTC, johnjaylward commented on src/main/java/org/json/XML.java
> -        if ("".equals(string)) {
As this is a public method, the contract has to remain the same. This means supporting a `null` parameter value.

2022-08-13 17:58 UTC, stleary commented
Closed due to lack of activity.

2022-08-13 17:58 UTC, closed without merging