avoid using recursion in for JSONML and JSONTokener
stleary/JSON-java pull request #726
Opened 2023-02-12 16:00 UTC by cleydyr

Fixes #722

2023-02-12 22:50 UTC, stleary commented
Nice work!
A description of what was changed and why it was changed would be helpful. 
The changes to JSONML should probably not be included in this pull request, since that file is being updated in #723 and will be accepted before this PR. 
Good to see the unit tests did not find any regressions. 
What is needed to ensure that there have been no functional changes - i.e. that the new code produces exactly the same results as the old? I don't think the current unit tests are sufficient to confirm this.

2023-02-13 19:25 UTC, cleydyr commented
No problem. I can drop the first commit, which is related to JSONML.

The commits prefixed by `refactoring` can be proven to make no functional changes.

The last commit is trickier, as I tried to simulate what the call stack does: push local variables (at least the relevant ones) and the instruction into the stack, but it would be hard to prove that the two algorithms yield the same results.

So, I see two alternatives: 1) generate a considerable amount of data in the JSON format that corresponds to the grammar that this parser obeys (the grammar should be defined formally, as in https://www.json.org/json-en.html) and add tests to _reduce_ the likelihood of missing a case (never eliminating it, of course) or 2) assume the tests we have currently are "good enough" and, should anybody find a regression, fix the parser accordingly.

What do you think?

2023-02-14 05:26 UTC, stleary commented
A lot of code was updated. The unit tests are good for catching regressions but for this PR I don't think that is enough. Probably needs a careful review and some additional unit testing. Otherwise, I think someone could fairly ask why not create a ParserConfiguration class similar to XML and JSONML and avoid all the refactoring.

2023-02-20 08:06 UTC, javadev commented on src/test/java/org/json/junit/JSONArrayTest.java
> -        fail("Excepected Exception.");
Why test was removed?

2023-02-20 08:07 UTC, javadev commented on src/test/java/org/json/junit/JSONObjectTest.java
> -        fail("Excepected Exception.");
Test should not be removed

2023-02-20 08:08 UTC, javadev commented
I see so many changes and few unit tests

2023-02-20 08:08 UTC, javadev commented
This branch has conflicts that must be resolved

2023-02-20 08:29 UTC, cleydyr commented on src/test/java/org/json/junit/JSONArrayTest.java
> -        fail("Excepected Exception.");
Because with my changes a stack overflow is not expected to happen as the algorithm to parse strings to JSON is not recursive anymore. So the test would fail 100% of the time, instead of intermittently as it does currently.

2023-02-20 08:30 UTC, cleydyr commented on src/test/java/org/json/junit/JSONObjectTest.java
> -        fail("Excepected Exception.");
Why?

2023-02-20 15:18 UTC, javadev commented on src/test/java/org/json/junit/JSONArrayTest.java
> -        fail("Excepected Exception.");
It may be changes in test

2023-02-20 15:19 UTC, javadev commented on src/test/java/org/json/junit/JSONObjectTest.java
> -        fail("Excepected Exception.");
It is not good remove tests after code changes

2023-02-20 15:32 UTC, JosephWitthuhnTR commented on src/test/java/org/json/junit/JSONArrayTest.java
> -        fail("Excepected Exception.");
For both of these, these tests looks like they were **testing to make sure that a stack overflow occurred**. So these tests "pass" if the bug isn't fixed, but will fail if the bug is fixed. So... not the best test to leave in.

That said, a better test might be to ensure that the use case that previously threw an exception no longer throws an exception? So instead of removing the tests entirely, update them to test that use case, but ensure that no exception is thrown instead of ensuring that an exception is thrown?

(I'm not a maintainer on this project, just my two cents as someone who was watching this CVE.)

2023-02-25 16:23 UTC, melloware approved these changes

2023-03-31 10:54 UTC, javadev requested changes
There are many code changes and few unit tests

2023-04-17 09:53 UTC, javadev commented
This branch has conflicts that must be resolved

2023-04-27 15:04 UTC, javadev commented
This branch has conflicts that must be resolved

2023-04-27 15:49 UTC, closed without merging

2023-04-27 15:50 UTC, cleydyr commented
I'll send this again when I rebase and have some test coverage.