Setup java 11 as minimum version
stleary/JSON-java pull request #741
Opened 2023-05-29 07:37 UTC by javadev

2023-05-29 08:03 UTC, javadev commented
![image](https://github.com/stleary/JSON-java/assets/348496/fe35845b-36b1-4c1d-9411-eeed854d621d)

2023-06-07 10:27 UTC, michael-o commented
This is really unapropriate for a low-level library. There is zero benefit from a user's perspective.

2023-06-07 10:30 UTC, javadev commented
> This is really inapropriate for a low-level library. There is zero benefit from a user's perspective. Java 8 is more than enough.

I understand your perspective, but I respectfully disagree. While Java 8 may be sufficient for some use cases, it is important to consider security implications when choosing a minimum secure version for a low-level library.

Java 11 introduced several security enhancements and bug fixes compared to Java 8. It includes updates to the Java Security Architecture, improvements to the TLS protocol, and the introduction of the HTTP/2 protocol, among other security-related features.

By requiring a minimum secure version like Java 11, developers ensure that their library takes advantage of the latest security improvements and patches. This can help prevent potential vulnerabilities and protect users' systems from security threats.

Furthermore, as time progresses, older Java versions may become more susceptible to security risks as new vulnerabilities are discovered. Requiring a more recent version ensures that the library remains compatible with modern security standards.

While there might be an initial cost associated with upgrading to a newer version, the long-term benefits of improved security outweigh the inconvenience. It's essential to prioritize security in software development, especially when developing low-level libraries that could be utilized in various contexts.

Ultimately, the decision of the minimum required version depends on the specific needs and considerations of the library and its users. However, from a security standpoint, Java 11 or a newer version would be a more appropriate choice than Java 8 for a low-level library.

2023-06-07 10:32 UTC, michael-o commented
> > This is really inapropriate for a low-level library. There is zero benefit from a user's perspective. Java 8 is more than enough.
> 
> I understand your perspective, but I respectfully disagree. While Java 8 may be sufficient for some use cases, it is important to consider security implications when choosing a minimum secure version for a low-level library.
> 
> Java 11 introduced several security enhancements and bug fixes compared to Java 8. It includes updates to the Java Security Architecture, improvements to the TLS protocol, and the introduction of the HTTP/2 protocol, among other security-related features.
> 
> By requiring a minimum secure version like Java 11, developers ensure that their library takes advantage of the latest security improvements and patches. This can help prevent potential vulnerabilities and protect users' systems from security threats.
> 
> Furthermore, as time progresses, older Java versions may become more susceptible to security risks as new vulnerabilities are discovered. Requiring a more recent version ensures that the library remains compatible with modern security standards.
> 
> While there might be an initial cost associated with upgrading to a newer version, the long-term benefits of improved security outweigh the inconvenience. It's essential to prioritize security in software development, especially when developing low-level libraries that could be utilized in various contexts.
> 
> Ultimately, the decision of the minimum required version depends on the specific needs and considerations of the library and its users. However, from a security standpoint, Java 11 or a newer version would be a more appropriate choice than Java 8 for a low-level library.

What? How does all this matter for a library which parses JSON? TLS? HTTP/2? Totally unrelated. OpenJDK 8 receives all necessary security fixes until 2030. At the end, as a library developer I should not impose something which isn't required from a technical PoV.

2023-06-07 10:36 UTC, javadev commented
Twistlock, a security analysis platform, has flagged Java 8 as insecure despite its long-term support and security fixes until 2030. While Java 8 may still receive critical security updates, it's worth considering the recommendations provided by Twistlock to ensure optimal security for your low-level library. Ultimately, as a library developer, it's important to weigh the technical requirements, user needs, and security concerns when determining the minimum required Java version.

2023-06-07 10:54 UTC, javadev commented
We can choose to wait for years and continue to maintain Java 1.6 as the minimum required JDK version.

2023-06-07 10:56 UTC, michael-o commented
> We can choose to wait for years and continue to maintain Java 1.6 as the minimum required JDK version.

It'd be advisable to release a last 1.6 version with last fixes and move to Java 8 to have a maintained stack with a new (at least) minor version. Here, I doubt that people will object Java 8.

2023-06-07 11:00 UTC, javadev commented
This pull request was specifically created for Java 11, indicating that it targets the features and functionality available in that version. Whether the pull request will be closed, merged, or remain open depends on the project maintainers and their evaluation of its compatibility and relevance. While it's possible that some individuals may prefer Java 8, the decision ultimately lies with the project maintainers and their consideration of the pull request's alignment with the project's goals and requirements.

2023-06-07 15:53 UTC, stleary commented
I think it's reasonable to require Java 8 if there is a valid PR that uses it. 
For example, #737 would be a good candidate to add an API method that works with Streams, which is only available from Java 8.
Once this is ready I can do a final v6 release, followed by a v8 build. 
Will let the v8 build sit for a month or so in case there are concerns.
I don't think v11 is advisable since some projects, including my current and previous employers, are still stuck on v8.
I think Android is no longer an issue due to its good-enough support for v8.

2023-08-25 19:15 UTC, johnjaylward commented
I really don't see a need to drop Java8 at this time. The library is not today using any features above Java 1.6, and form a Bytecode perspective, there isn't a good reason to limit to Java11+. As stated elsewhere in this thread and other issues, Java8 will be around for a long time.

Just because there are valid Application use-cases for using Java11+, this application really does not have a use case for forcing that JVM restriction on downstream developers at this time.

I would not recommend merging this unless the v8 build is put back in with the source and target outputs being v8.

Also, the pipeline.yml can get cleaned up quite a bit. There is no reason to keep the section that was used for the old 1.6 code. Simply using the section dedicated to JVM 8+ would be advisable. I would also not build/test against every JVM version out there. Sticking with the LTS versions (8,11,17) only is a valid approach for libraries.

2023-08-25 19:22 UTC, johnjaylward requested changes

2023-08-25 19:22 UTC, johnjaylward commented on .github/workflows/pipeline.yml
> +  build-11:
This whole pipeline file needs a lot of cleanup. The entire old "build-1_6" (original lines 14 through 39) section should just be deleted.

Keep just the "Build" section

2023-08-25 19:22 UTC, johnjaylward commented on .github/workflows/pipeline.yml
> +        java: [ 11, 17 ]
Add 8 back in here.

2023-08-25 19:22 UTC, johnjaylward commented on pom.xml
> +                    <source>11</source>
Source and target should both be set back to 1.8.

The changes from #761 will also need to be incorporated once merged to master

2023-08-25 19:22 UTC, johnjaylward commented on src/test/java/org/json/junit/JSONObjectTest.java
> -        // sorry, mockito artifact
If we aren't going to validate the Mockito artifacts here, then I see no reason to use Mockito for this test case at all. It adds no benefit if we remove the assertions against it.

2023-08-25 19:29 UTC, johnjaylward commented on src/test/java/org/json/junit/JSONObjectTest.java
> -        // sorry, mockito artifact
I understand these checks don't work against the new version of Mockito which is required for Java 17+, If you can please try to find a solution that will do similar validations.

2023-08-28 14:43 UTC, johnjaylward requested changes

2023-08-28 14:43 UTC, johnjaylward commented on .github/workflows/pipeline.yml
> +  build-8:
This whole `build-8` section still needs to be deleted. All it does is waste time in the pipeline.

2023-08-28 14:44 UTC, johnjaylward commented on .github/workflows/pipeline.yml
> +  build-8:
lines 13-41 should be deleted.

2023-08-28 15:45 UTC, johnjaylward approved these changes
I'm OK with this set of changes as long as @stleary agrees with the direction.

2023-08-28 16:08 UTC, johnjaylward commented
Why are you pushing more commits after approval? You are making me feel like I'm wasting my time.

2023-08-28 16:49 UTC, javadev commented
I noticed that the master branch isn't currently up to date. Therefore, I took the initiative to rebase the branch with the most current version.

2023-08-28 16:51 UTC, javadev commented
> 

I apologize if my actions have caused any inconvenience. The reason for pushing additional commits after approval is to ensure the code's integrity and address any potential issues that may have been missed earlier. Please know that your time and contributions are valued, and I'm committed to delivering the best quality work. If you prefer a different approach or have specific concerns, please feel free to share them, and I'll do my best to accommodate your preferences.

2023-08-28 21:25 UTC, johnjaylward commented
I got an email that looked like this:

> [@javadev](https://github.com/javadev) requested your review on: [#741](https://github.com/stleary/JSON-java/pull/741) Configure Java 8 as the minimum required version.

So I re-reviewed and approved, then you pushed again... then I got another email...

If it's automated by GitHub, then there isn't much you could have done about it I suppose, but if there was a button you hit to re-request review, I'd ask that you refrain from hitting the button before finalizing your changes.

The other option would be to place the PR in draft mode, so that reviewers know you are still working out changes.

2023-08-28 21:27 UTC, johnjaylward approved these changes

2023-08-29 00:16 UTC, stleary commented
The maven build works fine with Java 8, but this error with gradlew. Did something get missed?
![image](https://github.com/stleary/JSON-java/assets/5107558/7fec07c7-9636-4130-9239-51fa26804495)

2023-08-29 00:25 UTC, javadev commented
> The maven build works fine with Java 8, but this error with gradlew. Did something get missed? ![image](https://user-images.githubusercontent.com/5107558/263863101-7fec07c7-9636-4130-9239-51fa26804495.png)

I have prepared a solution.

2023-08-29 00:45 UTC, stleary commented
**What problem does this code solve?**
Update builds to support Java 8 and above.
Java 6 and 7 users will need to stay with v20230618.

**Risks**
Moderate

**Changes to the API?**
No

**Will this require a new release?**
Yes

**Should the documentation be updated?**
No

**Does it break the unit tests?**
No

**Was any code refactored in this commit?**
No

**Review status**
**APPROVED**
Starting 3-day comment window. 
This change will be included in the next release, which will also need to include a useful feature that requires Java 8.

2023-09-01 08:34 UTC, javadev commented
[johnjaylward](https://github.com/johnjaylward) reviewed [3 days ago](https://github.com/stleary/JSON-java/pull/741#pullrequestreview-1599351650)

2023-09-03 15:45 UTC, stleary commented
Will merge when we have a feature that requires Java 8, e.g. #737

2023-09-03 21:09 UTC, johnjaylward approved these changes

2023-09-03 21:12 UTC, johnjaylward commented
> Will merge when we have a feature that requires Java 8, e.g. #737

I think that's putting the horse (v8 support) after the cart (v8 features). Merging this will allow version 8 features to be implemented.

I think this should be merged before features. Also, if this waits too long it will become stale and a pain to maintain if there are conflicting changes.

2023-09-03 22:16 UTC, stleary commented
Good point @johnjaylward

2023-09-03 22:16 UTC, stleary approved these changes

2023-09-03 22:17 UTC, merged